name: Daily PolyRatings Data Collection

on:
  # Run daily at 6 AM UTC (adjust timezone as needed)
  schedule:
    - cron: '0 6 * * *'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  collect-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create data directories
      run: |
        mkdir -p data/main
        mkdir -p data/tracking
        
    - name: Run data collection
      run: |
        python get_professor_ids.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Add only main data files (tracking files are ignored)
        git add data/main/
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update PolyRatings data - $(date '+%Y-%m-%d %H:%M:%S')"
          git push
        fi
        
    - name: Upload tracking files as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: polyratings-tracking-${{ github.run_number }}
        path: data/tracking/
        retention-days: 30
